### ISSUE TITLE
Provide @type for typescript

### ISSUE THREAD

**Issue by Wtango** [flitbit/json-ptr#15]
This project is so helpful, it's better to provide the @type for using in typescript.

**Comment by zanona** [comment]
Yes, please! :)

**Comment by treybrisbane** [comment]
I've just written some typings for this. 🙂
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42333.

**Comment by sbusch** [comment]
@treybrisbane That's really great, thanks! I will test them as soon as they got merged :-)

**Comment by flitbit** [comment]
This past weekend I rewrote the whole library as Typescript. I've still got to rewrite examples and such so it isn't versioned up yet. Take a look and let me know if you experience any problems.

```bash
npm i json-ptr@1.2.0-ts.da6e2a1
```
It is definitely typed.

**Comment by treybrisbane** [comment]
Wait... Seriously? 😆

Well I'm guessing I should go decline my DefinitelyTyped PR? What's the ETA on the TypeScript release?

In case it's relevant, I did some stuff with conditional types to make some return types dependent on arguments. Maybe take a brief look and see if you can use anything? I tend to be pretty meticulous when typing stuff, so maybe it'll be useful. 🙂

**Comment by treybrisbane** [comment]
@flitbit I've taken a look at the TS branch, and it's looking pretty solid so far! 🙂

I definitely think we should tighten up the typings though, as they're currently very loose. Some improvements we could make are:
- Using `unknown` instead of `any` where ever possible
    - `unknown` means "_could be any type, but you must explicitly check which type it is before you do anything with it_", whereas `any` means "_could be any type, you can do anything with it, and the compiler won't do any type checking at all_". As a result, `unknown` is greatly preferred due to its vastly better safety.
- Splitting the [`PointerPair`](https://github.com/flitbit/json-ptr/blob/81a66a906013c992d15096f8ff10ea6deacbec97/src/pointer.ts#L36) type into separate [JSON pointer](https://github.com/treybrisbane/DefinitelyTyped/blob/2b2bab01ef0c2deb78e0e53da8fedaed6d1d4f0f/types/json-ptr/index.d.ts#L14) and [URI fragment](https://github.com/treybrisbane/DefinitelyTyped/blob/2b2bab01ef0c2deb78e0e53da8fedaed6d1d4f0f/types/json-ptr/index.d.ts#L19) types, and [choosing which one to return based on the value of the `fragmentId` argument](https://github.com/treybrisbane/DefinitelyTyped/blob/2b2bab01ef0c2deb78e0e53da8fedaed6d1d4f0f/types/json-ptr/index.d.ts#L51)
    - In the types I made, I opted to use conditional types for this, but you can also use function overloading
    - If you want to use overloading, you'd need three overloads: One where `fragmentId` isn't passed (that returns the JSON pointer type), one where `fragmentId` is passed but is typed as `false` (that also returns the JSON pointer type), and one where `fragmentId` is passed and typed as `true` (that returns the URI fragment type).
- Using the built-in `Record` type ([example](https://github.com/treybrisbane/DefinitelyTyped/blob/2b2bab01ef0c2deb78e0e53da8fedaed6d1d4f0f/types/json-ptr/index.d.ts#L63)) rather than defining your own [`Dict` interface](https://github.com/flitbit/json-ptr/blob/81a66a906013c992d15096f8ff10ea6deacbec97/src/pointer.ts#L28)
- Avoiding generic types that only appear in the return position
    - E.g. the `R` types [here](https://github.com/flitbit/json-ptr/blob/81a66a906013c992d15096f8ff10ea6deacbec97/src/pointer.ts#L88), [here](https://github.com/flitbit/json-ptr/blob/81a66a906013c992d15096f8ff10ea6deacbec97/src/pointer.ts#L102), and [here](https://github.com/flitbit/json-ptr/blob/81a66a906013c992d15096f8ff10ea6deacbec97/src/pointer.ts#L274), and the `V` type [here](https://github.com/flitbit/json-ptr/blob/81a66a906013c992d15096f8ff10ea6deacbec97/src/pointer.ts#L195)
    - See [this thread](https://twitter.com/SeaRyanC/status/1205170798282960896) by one of TypeScript's maintainers to elaborate a bit on why
- Using a [type predicate](https://www.typescriptlang.org/docs/handbook/advanced-types.html#using-type-predicates) for the return type of [`isReference`](https://github.com/flitbit/json-ptr/blob/81a66a906013c992d15096f8ff10ea6deacbec97/src/pointer.ts#L260) ([example](https://github.com/treybrisbane/DefinitelyTyped/blob/2b2bab01ef0c2deb78e0e53da8fedaed6d1d4f0f/types/json-ptr/index.d.ts#L29))
- Considering some well-named type aliases rather than using things like `string` everywhere
    - Some aliases I defined were [`PathSegments`](https://github.com/treybrisbane/DefinitelyTyped/blob/2b2bab01ef0c2deb78e0e53da8fedaed6d1d4f0f/types/json-ptr/index.d.ts#L8), [`JsonStringPointer`](https://github.com/treybrisbane/DefinitelyTyped/blob/2b2bab01ef0c2deb78e0e53da8fedaed6d1d4f0f/types/json-ptr/index.d.ts#L10), [`UriFragmentIdentifierPointer`](https://github.com/treybrisbane/DefinitelyTyped/blob/2b2bab01ef0c2deb78e0e53da8fedaed6d1d4f0f/types/json-ptr/index.d.ts#L11), and [`Pointer`](https://github.com/treybrisbane/DefinitelyTyped/blob/2b2bab01ef0c2deb78e0e53da8fedaed6d1d4f0f/types/json-ptr/index.d.ts#L12)
    - These don't provide any additional safety, but can make the code a little more self-documenting

A couple of misc. other things that could also be improved are:
- Defining the `toString` methods for each of [`JsonPointer`](https://github.com/flitbit/json-ptr/blob/81a66a906013c992d15096f8ff10ea6deacbec97/src/pointer.ts#L255) and [`JsonReference`](https://github.com/flitbit/json-ptr/blob/81a66a906013c992d15096f8ff10ea6deacbec97/src/pointer.ts#L279) _inside the respective classes_, rather than as assignments to the class `prototype`
- Unifying the [declaration](https://github.com/flitbit/json-ptr/blob/81a66a906013c992d15096f8ff10ea6deacbec97/src/pointer.ts#L19) and [initialisation](https://github.com/flitbit/json-ptr/blob/81a66a906013c992d15096f8ff10ea6deacbec97/src/pointer.ts#L290) of the `descendingVisit` function

Happy to submit PRs for any of this stuff to help get it over the line! 🙂

**Comment by flitbit** [comment]
I appreciate the commentary. I'm only part way in on typescript so I really like your more seasoned analysis of this attempt.

Of your notes, the `Record` type had entered my brain-hole just last week, saw it in some code and went "ah ha!" -- I was trying to remember where I put that `Dict` type... now I know!

I would welcome the PR. Seriously dude, I appreciate the pointers (pun). I won't have time in my schedule to look again before next week, but hope to see it!

**Comment by flitbit** [comment]
@treybrisbane I've updated following along most of your typescript suggestions; LMK.

BTW, the "this thread" link goes to nowhere (rejected by the server). I really wanted to check that one out.

**Comment by treybrisbane** [comment]
Apologies for the delay; I've had a busy week!
I'll aim to take a look at your changes tomorrow evening.

As far as the link goes, it was a link to a tweet by Ryan Cavanaugh. Try this: https://twitter.com/SeaRyanC/status/1205170798282960896?s=20 (you'll probably have to then click on the tweet itself to see the various replies in which he elaborates)

**Comment by treybrisbane** [comment]
Apologies again for the delay!

I've put up [this PR](https://github.com/flitbit/json-ptr/pull/18) with a few improvements. Please take a look at it when you get a few minutes and let me know what you think. 🙂

**Comment by flitbit** [comment]
Supported at v1.3.0
