### ISSUE TITLE
Undocumented exported functions?

### ISSUE THREAD

**Issue by kevinoid** [flitbit/json-ptr#29]
The functions defined in [`src/util.ts`](https://github.com/flitbit/json-ptr/blob/v2.0.0/src/util.ts) are [exported](https://github.com/flitbit/json-ptr/blob/v2.0.0/src/index.ts#L6), but are not mentioned in [`README.md`](https://github.com/flitbit/json-ptr/blob/v2.0.0/README.md) and only [their signatures are documented by TypeDoc](https://flitbit.github.io/json-ptr/modules/_src_util_.html).   Could you clarify whether these are intended to be part of the public API?

Thanks,
Kevin

**Comment by cerebralkungfu** [comment]
They are indeed, purposefully exported, as part of the intended public API so that other utilities might be built on them if they are useful. Those are the guts really... the classes make use of those utility functions and the tests cover them many times over. That said, I really should get them documented and explained as time permits.
