### ISSUE TITLE
Documentation unavailable (http 404)

### ISSUE THREAD

**Issue by gmw-web** [flitbit/json-ptr#44]
Documentation for both the 'JsonPointer' and 'JsonReference' class appears to be unavailable.
**To reproduce:**
Go to the documentation website https://flitbit.github.io/json-ptr/
Click 'JsonPointer' on the right hand side
See HTTP 404.

**Comment by cerebralkungfu** [comment]
Yeah, I've been aware of this for a little while. The link is broken because the documents have mixed case but jekyll (used by github) doesn't resolve mismatch case. Jekyll is accurate, that's what the URI spec says, that case matters, so I need to investigate other documentation tools... when time allows.

Anybody want to write a tsdoc post-processor that rewrites all of the embedded links to lower-case?

**Comment by cerebralkungfu** [comment]
Fixed. Hell, that was dumb... mac file system is case insensitive by default. I forget that some times. Removed in one commit, re-generated in the next. Working again.
